### ISSUE TITLE
[Tracker] WIP Features for torchao v0.2

### ISSUE THREAD

**Issue by supriyar** [pytorch/ao#132]
## New Features

- [ ] Auto Quant + Auto Tuner @HDCharles @cpuhrsch 
    - [x] Auto quant API with support for int8 weight-only and dynamic quant 
    - [ ] [DELAYED] Benchmarks for auto quant on [pytorch benchmark's inference quant pane](https://hud.pytorch.org/benchmark/compilers)
    - [ ] Kernel auto tuner that works with auto quant API with results on SAM and benchmarks on torchbench
- [x] C++ CPU extensions in torchao/kernel/cpu @msaroufim  https://github.com/pytorch/ao/tree/main/torchao/csrc
- [x] C++ CUDA extensions in torchao/kernel/cuda w/ A10G and manylinux support in CI @msaroufim https://github.com/pytorch/ao/pull/176
- [ ] Int8 + 2:4 sparse inference APIs and results on SAM @jcaip 
- [ ] Fast sparse training @jcaip 
- [ ] Explore adding HQQ 4/3/2-bit quant to torchao @HDCharles @mobicham 
- [ ] [WIP] Consolidating workflows to use tensor subclass @jerryzh168 
- [x] NF4 FSDP support https://github.com/pytorch/ao/pull/150 @weifengpy 

## Better Engineering

- [x] Remove _is_gpt_fast flag @jerryzh168 
- [ ] Add rudimentary shape checks (e.g. multiple of 16 constraints)
- [ ] Generic test guards for sm80 (bfloat16) and CPU-only environment
- [x] [done for 0.2] Dedup https://github.com/pytorch-labs/ao/blob/046dc985de6d5eac05c6575cc71505687e3aadf1/torchao/quantization/quant_primitives.py#L23-L42 @jerryzh168 
- [x] Better sparsity docs @jcaip 
- [x] Documentation of torchao features @msaroufim 
- [ ] GPTQ Refactor 

## Repo Health
- [x] Setup docs page pytorch.org/ao @svekars 
- [x] OSS -> fbcode sync (setup difftrain) @jerryzh168 and Jon from OSS team
- [ ] Don't cause a "import error" when someone is using a feature unsupported by e.g. torch 2.1.2 (e.g. https://github.com/pytorch-labs/ao/blob/046dc985de6d5eac05c6575cc71505687e3aadf1/torchao/quantization/quant_primitives.py#L42 will cause an import error if someone tries to use torchao.quantization.quant_primitives.per_token_dynamic_quant on 2.2.2
- [x] Enable test_8da4w_quantize for 2.4 @cpuhrsch

**Comment by supriyar** [comment]
tracking 0.3 in https://github.com/pytorch/ao/issues/252
