### ISSUE TITLE
Update the CI/CD to use AWS G6 instance

### ISSUE THREAD

**Issue by jainapurva** [pytorch/ao#611]
For float8, testing needs to be performed on g6.4x machine, hence a new instance is added to the CI/CD pipeline for only float8 tests https://github.com/pytorch/ao/pull/587. If we change the current default machine from g5.12x to g6.4x, we'll be having the following benefits:

**Cost efficient:** We could reduce the CI cost by approx 4x.
g5.12x: $5.672 per hour [g5.12x prices](https://aws.amazon.com/ec2/instance-types/g5/)
g6.4x: $1.323 per hour [g6.4x prices](https://aws.amazon.com/ec2/instance-types/g6/)

**Unified pipeline:** We would reduce the need for adding different machines for different dtypes.

**TODO:**
- [ ] Update default test machine to `amz2023.linux.g6.4xlarge.experimental.nvidia.gpu`
- [ ] Update tests to support the new machine:
  - [ ] test/sparsity/test_structured_sparsifier.py::TestBaseStructuredSparsifier::test_prune_linear_linear
  - [ ] test/sparsity/test_structured_sparsifier.py::TestBaseStructuredSparsifier::test_prune_linear_bias_linear
  - [ ] test/sparsity/test_structured_sparsifier.py::TestBaseStructuredSparsifier::test_prune_linear_activation_linear
  - [ ] test/prototype/mx_formats/test_mx_tensor.py::test_to_mx_from_mx_compile_numerics[False-hp_dtype1-elem_dtype1]
  - [ ] test/prototype/test_low_bit_optim.py::TestFSDP2::test_fsdp2
  - [ ] test/integration/test_integration.py::TestSubclass::test_int8_weight_only_quant_with_freeze
  - [ ] test/dtypes/test_nf4.py::TestQLoRA::test_qlora_fsdp2
